- name: colored console for all user
  tags:
    - colored
  copy:
    src: color_ps.sh
    dest: /etc/profile.d/color_ps.sh
    owner: vagrant
    group: vagrant
    mode: 0644

- name: colored nano for apache2 conf files
  tags:
    - colored
  copy:
    src: apache2.nanorc
    dest: /usr/share/nano/apache2.nanorc
    owner: vagrant
    group: vagrant
    mode: 0644

- name: colored nano for vagrant user
  tags:
    - colored
  copy:
    src: .nanorc
    dest: /home/vagrant/.nanorc
    owner: vagrant
    group: vagrant
    mode: 0644

- name: colored nano for root user
  tags:
    - colored
  copy:
    src: .nanorc
    dest: /root/.nanorc
    owner: root
    group: root
    mode: 0644