- name: Downloading Composer installer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "{{ tmp_dir }}/composer-setup.php"

- name: Running installer
  shell: "php composer-setup.php --quiet"
  args:
    chdir: "{{ tmp_dir }}/"

- name: Copying Composer to /usr/local/bin/
  copy:
    src: "{{ tmp_dir }}/composer.phar"
    dest: "/usr/local/bin/composer"
    owner: vagrant
    group: vagrant
    mode: 0755