- name: Installing common utilites (unzip, net-tools, zip, mc, wget, nano, git)
  yum:
    name:
      - unzip
      - net-tools
      - zip
      - mc
      - wget
      - nano
      - git
    state: present

- name: Create directory for downloads
  tags:
    - xdebug
  file:
    path: "{{ tmp_dir }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0775
    recurse: yes

- name: Installing epel
  yum:
    name: epel-release
    state: present

- include: colored.yml
  when: colored

- include: php.yml
  when: php

- include: apache.yml
  when: apache

- include: xdebug.yml
  when: php, xdebug

- include: adminer.yml
  when: adminer

- include: composer.yml
  when: php, composer

    - include: phpinfo.yml
      when: phpinfo