- name: Downloading Xdebug
  tags:
    - xdebug
  get_url:
    url: "http://xdebug.org/files/xdebug-{{ xdebug_ver }}.tgz"
    dest: "{{ tmp_dir }}/xdebug-{{ xdebug_ver }}.tgz"

- name: unarchive Xdebug
  tags:
    - xdebug
  unarchive:
    src: "{{ tmp_dir }}/xdebug-{{ xdebug_ver }}.tgz"
    dest: "{{ tmp_dir }}"
    mode: 0755
    group: vagrant
    owner: vagrant

- name: Installing php packages for phpize
  tags:
    - xdebug
  yum:
    enablerepo: remi,remi-php72
    name:
      - php-devel
      - gcc
    state: present

- name: compiling Xdebug
  tags:
    - xdebug
  shell: "cd {{ tmp_dir }}/xdebug-{{ xdebug_ver }}/ && phpize && ./configure && make"

- name: Copying Xdebug module
  tags:
    - xdebug
  copy:
    src: "{{ tmp_dir }}/xdebug-{{ xdebug_ver }}/modules/xdebug.so"
    dest: "/usr/lib64/php/modules/xdebug.so"

- name: Activation of the Xdebug
  tags:
    - xdebug
  lineinfile:
    name: "/etc/php.ini"
    line: "zend_extension = /usr/lib64/php/modules/xdebug.so"

- name: Restarting web-server
  tags:
    - xdebug
  shell: "systemctl restart httpd"